# export ANTIGEN_LOG="/Users/danthompson/.antigen.log"

# export ADD_ALIAS_FILE="/Users/danthompson/Code/dotfiles/zsh_omz/aliases.zsh"

## path
# If you come from bash you might have to change your $PATH.
export FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
export PATH="$HOME/.local/bin:$PATH"

# uv


# Would you like to use another custom folder than $ZSH/custom?
export ZSH_CUSTOM=/Users/danthompson/Code/dotfiles/zsh_omz

## omz
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# # plugins using antigen
# export ANTIGEN_LOG=/Users/danthompson/Code/dotfiles/zsh_omz/antigen.log

source ~/.zsh/antigen.zsh

antigen use oh-my-zsh

antigen theme romkatv/powerlevel10k

# omz plugins
antigen bundle jsontools # maybe done by antigen # there was an antigen option
antigen bundle aws # completions # there was an antigen option
antigen bundle ag
antigen bundle autopep8
antigen bundle copypath
antigen bundle copyfile
antigen bundle tmux
antigen bundle copybuffer
antigen bundle direnv
antigen bundle dirhistory
antigen bundle git
antigen bundle macos
antigen bundle aliases
antigen bundle alias-finder
# antigen bundle alias-maker
# antigen bundle ripgrep
antigen bundle git-prompt
antigen bundle Tarrasch/zsh-autoenv

# antigen bundle fasd
# probably disabled
# antigen bundle fzf

# disabled
# antigen bundle autojump (in favor of fasd)
# antigen bundle z (in favor of fasd)
# antigen bundle ansible (aliases)
# antigen bundle autoenv (enables this tool)
# antigen bundle thefuck
# antigen bundle sudo (but i need to change the keybinding)

# other zsh plugins
antigen bundle zdharma-continuum/zsh-diff-so-fancy --branch=main
# antigen bundle djui/alias-tips
# antigen bundle MefitHp/alias-maker@main
# antigen bundle esc/conda-zsh-completion
antigen bundle zsh-users/zsh-completions
antigen bundle sunlei/zsh-ssh
antigen bundle Aloxaf/fzf-tab
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle mafredri/zsh-async --branch=main

# disabled
# antigen bundle fdellwing/zsh-bat
# antigen bundle lincheney/fzf-tab-completion
# antigen bundle SleepyBag/fuzzy-fs # no longer working
# antigen bundle aws/aws-cli
# antigen bundle mm/jsontools

antigen apply
source $ZSH/oh-my-zsh.sh


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Enable color
set t_Co = 256

ssh-add ~/.ssh/id_raspberry_pi > /dev/null 2>&1
autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/danthompson/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/danthompson/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/danthompson/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/danthompson/google-cloud-sdk/completion.zsh.inc'; fi


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Add /usr/local/bin to the PATH
export PATH="/Users/danthompson/go/bin:$PATH"

eval "$(mcfly init zsh)"

source /Users/danthompson/.config/broot/launcher/bash/br


PATH="/Users/danthompson/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/Users/danthompson/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/danthompson/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/danthompson/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/danthompson/perl5"; export PERL_MM_OPT;

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias claude="/Users/danthompson/.claude/local/claude"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Created by `userpath` on 2025-04-18 19:43:28
export PATH="$PATH:/Users/danthompson/Library/Application Support/hatch/pythons/3.12/python/bin"

# Shell-GPT integration ZSH v0.2
_sgpt_zsh() {
if [[ -n "$BUFFER" ]]; then
    _sgpt_prev_cmd=$BUFFER
    BUFFER+="⌛"
    zle -I && zle redisplay
    BUFFER=$(sgpt --shell <<< "$_sgpt_prev_cmd" --no-interaction)
    zle end-of-line
fi
}
zle -N _sgpt_zsh
bindkey ^l _sgpt_zsh
# Shell-GPT integration ZSH v0.2

# Added by Windsurf
export PATH="/Users/danthompson/.codeium/windsurf/bin:$PATH"
