## path
# If you come from bash you might have to change your $PATH.
export FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
export PATH=$HOME/.local/bin:$PATH

# Would you like to use another custom folder than $ZSH/custom?
export ZSH_CUSTOM=/Users/danthompson/Code/dotfiles/zsh_omz

## omz
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# # plugins using antigen
export ANTIGEN_LOG=/Users/danthompson/Code/dotfiles/zsh_omz/antigen.log

source ~/.zsh/antigen.zsh

antigen use oh-my-zsh

antigen theme romkatv/powerlevel10k

# omz plugins
antigen bundle jsontools # maybe done by antigen # there was an antigen option
antigen bundle aws # completions # there was an antigen option
antigen bundle ag
antigen bundle autopep8
antigen bundle copypath
antigen bundle copyfile
antigen bundle copybuffer
antigen bundle dirhistory
antigen bundle git
antigen bundle macos
antigen bundle aliases
antigen bundle alias-finder
antigen bundle ripgrep
antigen bundle git-prompt
antigen bundle Tarrasch/zsh-autoenv

# antigen bundle fasd
# probably disabled
# antigen bundle fzf

# disabled
# antigen bundle autojump (in favor of fasd)
# antigen bundle z (in favor of fasd)
# antigen bundle ansible (aliases)
# antigen bundle autoenv (enables this tool)
# antigen bundle thefuck
# antigen bundle sudo (but i need to change the keybinding)

# other zsh plugins
antigen bundle zdharma-continuum/zsh-diff-so-fancy --branch=main
antigen bundle esc/conda-zsh-completion
antigen bundle zsh-users/zsh-completions
antigen bundle sunlei/zsh-ssh
antigen bundle Aloxaf/fzf-tab
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle mafredri/zsh-async --branch=main

# disabled
# antigen bundle fdellwing/zsh-bat
# antigen bundle lincheney/fzf-tab-completion
# antigen bundle SleepyBag/fuzzy-fs # no longer working
# antigen bundle aws/aws-cli
# antigen bundle mm/jsontools

antigen apply
source $ZSH/oh-my-zsh.sh


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Enable color
set t_Co = 256

ssh-add ~/.ssh/id_raspberry_pi > /dev/null 2>&1
autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/danthompson/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/danthompson/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/danthompson/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/danthompson/google-cloud-sdk/completion.zsh.inc'; fi

